### ISSUE TITLE
Lidar centre vs pointcloud projection

### ISSUE THREAD

**Issue by lundstrom14** [acfr/cam_lidar_calibration#10]
Hi, thanks for a great tool.

I'm wondering why the lidar centre looks to be projected spot on, but the resulting pointcloud is way off target. 
I'm using a wide angle lens (74 degree fov), but should have relatively low distortion. 

Even if the result is expected to behave worse at the camera edges this much re-projection error for the pointcloud is very unexpected. Is the lidar centre projected differently?

```
Mean reprojection error across  31 samples
- Error (pix) =  9.391 pix, stdev =  5.864
- Error (mm)  = 32.677 mm , stdev = 18.313
```
 
![Screenshot from 2021-12-14 11-55-49](https://user-images.githubusercontent.com/45545915/145992519-4c2bcae6-69c2-4b22-acc1-fd8e104b912e.png)

Thank you,

**Comment by darrenjkt** [comment]
It does appear to have low distortion but you can't really be sure that it doesn't affect the calibration. Double-check the distortion matrix in your camera driver and you'll have to implement a rectification of the image in this repo.  

Also, you should have an open area for capturing chessboard samples. Make sure you get poses that span the width of the image frame, and also which go from near to far. If you don't have chessboard poses in the extremities of the image, it may not find a good calibration. Make sure you also included poses where the chessboard is tilted up and down in order to get more varied normals.
