### ISSUE TITLE
RANSAC PCL erro

### ISSUE THREAD

**Issue by mendoza-G** [acfr/cam_lidar_calibration#17]
![image](https://user-images.githubusercontent.com/81526517/163744670-24af5574-bc7e-4b62-9eaf-86b26a47507b.png)
![image](https://user-images.githubusercontent.com/81526517/163745106-10665287-ee41-4cbc-ab31-1a8de2eb1cdf.png)

This is the erro happened, it seemed to be the issue of setting threshold. And I found that the value in this project was set to 0.004.  Should I change the value? Thanks!

**Comment by mendoza-G** [comment]
I' m using robosence M1 lidar, the points are more intensive. Does the brute-force approach take more time? I stucked at "capturing the sample" after clicked the CAPTURE button.

**Comment by darrenjkt** [comment]
We tried calibrating a Robosense RS-LIDAR-32 using this tool but we found that it was particularly hard to fit the board using RANSAC due to large distance errors by the lidar. E.g. the distance on black and white vary quite a bit, making the board not very planar in 3D. 

You could adjust the distance threshold as you pointed out but it can lead to a less accurate calibration. However, I guess you could use that as a starting point to tweak the parameters.
